/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.anuncios.telas;

import br.com.anuncios.beans.Anuncios;
import br.com.anuncios.dao.AnunciosDAO;
import br.com.anuncios.dao.AnunciosDAO.DateValidator;
import javax.swing.JOptionPane;

/**
 * Classe principal da tela de cadastro de anúncios.
 *
 * @author Eliaquim S. Macedo.
 */
public class TelaCadastro extends javax.swing.JInternalFrame {

    /**
     * Método construtos da classe TelaCadastro, cria um formulário de cadastro
     * de anúncios.
     *
     * @author Eliaquim S. Macedo.
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorDia = new javax.swing.JTextField();
        txtDataFim = new javax.swing.JTextField();
        txtDataInicio = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        txtNomeAnuncio = new javax.swing.JTextField();
        btnCadCreate = new javax.swing.JButton();
        btnCadUpdate = new javax.swing.JButton();
        btnCadDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtIdAnuncios = new javax.swing.JTextField();
        txtAnuncioPesquisar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de anúncios");
        setPreferredSize(new java.awt.Dimension(1059, 598));

        jLabel1.setText("* Nome do Anúncio");

        jLabel2.setText("* Nome do Cliente");

        jLabel3.setText("Data de Início");

        jLabel4.setText("Data de Término");

        jLabel5.setText("Valor Investido por Dia");

        btnCadCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/anuncios/icones/adicionar.png"))); // NOI18N
        btnCadCreate.setToolTipText("Adicionar");
        btnCadCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadCreate.setPreferredSize(new java.awt.Dimension(80, 80));
        btnCadCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCreateActionPerformed(evt);
            }
        });

        btnCadUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/anuncios/icones/editar.png"))); // NOI18N
        btnCadUpdate.setToolTipText("Alterar");
        btnCadUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadUpdate.setPreferredSize(new java.awt.Dimension(80, 80));
        btnCadUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUpdateActionPerformed(evt);
            }
        });

        btnCadDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/anuncios/icones/deletar.png"))); // NOI18N
        btnCadDelete.setToolTipText("Excluir");
        btnCadDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadDelete.setPreferredSize(new java.awt.Dimension(80, 80));
        btnCadDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDeleteActionPerformed(evt);
            }
        });

        jLabel6.setText("* Campos obrigatórios");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/anuncios/icones/buscar2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel7.setText("ID");

        txtIdAnuncios.setEnabled(false);

        jLabel8.setText("Digite o nome de um anúncio para buscar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdAnuncios, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtValorDia, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDataFim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAnuncioPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(btnCadCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(btnCadUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(btnCadDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(768, 768, 768)
                        .addComponent(jLabel6)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(513, 513, 513))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnBuscar)
                    .addComponent(txtAnuncioPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdAnuncios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNomeAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCadUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCadCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCadDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        setBounds(0, 0, 1059, 598);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCreateActionPerformed
        String nomeAnuncio = txtNomeAnuncio.getText();
        String nomeCliente = txtNomeCliente.getText();
        String dataInicio = txtDataInicio.getText();
        String dataFim = txtDataFim.getText();
        float valorDia;

        if (txtValorDia.getText().isEmpty()) {
            valorDia = 0;
        } else {
            valorDia = Float.parseFloat(txtValorDia.getText().replaceAll(",", "."));
        }

        Anuncios anuncio = new Anuncios();
        anuncio.setNOME_ANUNCIO(nomeAnuncio);
        anuncio.setNOME_CLIENTE(nomeCliente);
        anuncio.setDATA_INICIO(dataInicio);
        anuncio.setDATA_FIM(dataFim);
        anuncio.setVLR_INVESTIDO_DIA(valorDia);

        AnunciosDAO anuncioDAO = new AnunciosDAO();
        AnunciosDAO.DateValidator datavalida = anuncioDAO.new DateValidator();

        if (nomeAnuncio.isEmpty() || nomeCliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
        } else if (datavalida.isValid(dataInicio) && datavalida.isValid(dataFim)) {
            anuncioDAO.inserir(anuncio);
            JOptionPane.showMessageDialog(null, "Anúncio cadastrado com sucesso");
            txtNomeAnuncio.setText(null);
            txtNomeCliente.setText(null);
            txtDataInicio.setText(null);
            txtDataFim.setText(null);
            txtValorDia.setText(null);
        } else {
            JOptionPane.showMessageDialog(null, "As datas devem ser válidas e terem o formato dd/mm/aaaa");
        }
    }//GEN-LAST:event_btnCadCreateActionPerformed

    private void btnCadUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUpdateActionPerformed
        int idAnuncio = Integer.parseInt(txtIdAnuncios.getText());
        String nomeAnuncio = txtNomeAnuncio.getText();
        String nomeCliente = txtNomeCliente.getText();
        String dataInicio = txtDataInicio.getText();
        String dataFim = txtDataFim.getText();
        float valorDia;

        if (txtValorDia.getText().isEmpty()) {
            valorDia = 0;
        } else {
            valorDia = Float.parseFloat(txtValorDia.getText().replaceAll(",", ".").replace("R$ ",""));
        }

        Anuncios anuncio = new Anuncios();
        anuncio.setID_ANUNCIO(idAnuncio);
        anuncio.setNOME_ANUNCIO(nomeAnuncio);
        anuncio.setNOME_CLIENTE(nomeCliente);
        anuncio.setDATA_INICIO(dataInicio);
        anuncio.setDATA_FIM(dataFim);
        anuncio.setVLR_INVESTIDO_DIA(valorDia);

        AnunciosDAO anuncioDAO = new AnunciosDAO();
        AnunciosDAO.DateValidator datavalida = anuncioDAO.new DateValidator();

        // validação dos campos obrigatórios
        if (nomeAnuncio.isEmpty() || nomeCliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
        } else if (datavalida.isValid(dataInicio) && datavalida.isValid(dataFim)) {
            // atualizar a tabela de cadastro com os dados do formulário e confirma a alteração
            anuncioDAO.editar(anuncio);
            JOptionPane.showMessageDialog(null, "Anúncio alterado com sucesso");
            txtIdAnuncios.setText(null);
            txtNomeAnuncio.setText(null);
            txtNomeCliente.setText(null);
            txtDataInicio.setText(null);
            txtDataFim.setText(null);
            txtValorDia.setText(null);
            btnCadCreate.setEnabled(true); //linha para habilitar o botão adicionar
        } else {
            JOptionPane.showMessageDialog(null, "As datas devem ser válidas e terem o formato dd/mm/aaaa");
        }
    }//GEN-LAST:event_btnCadUpdateActionPerformed

    private void btnCadDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDeleteActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este anúncio?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            int id_anuncio = Integer.parseInt(txtIdAnuncios.getText());
            AnunciosDAO anuncioDAO = new AnunciosDAO();
            anuncioDAO.excluir(id_anuncio);
            JOptionPane.showMessageDialog(null, "Anúncio excluído com sucesso");
            txtIdAnuncios.setText(null);
            txtNomeAnuncio.setText(null);
            txtNomeCliente.setText(null);
            txtDataInicio.setText(null);
            txtDataFim.setText(null);
            txtValorDia.setText(null);
            btnCadCreate.setEnabled(true); //linha para habilitar o botão adicionar
        }
    }//GEN-LAST:event_btnCadDeleteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idPesquisa = txtAnuncioPesquisar.getText();
        AnunciosDAO anuncioDAO = new AnunciosDAO();
        Anuncios anuncio = anuncioDAO.consultar(idPesquisa);
        if (anuncio == null) {
            JOptionPane.showMessageDialog(this, "Não foram encontrados anúncios cadastrados");
            txtIdAnuncios.setText(null);
            txtNomeAnuncio.setText(null);
            txtNomeCliente.setText(null);
            txtDataInicio.setText(null);
            txtDataFim.setText(null);
            txtValorDia.setText(null);
        } else {
            txtIdAnuncios.setText(Integer.toString(anuncio.getID_ANUNCIO()));
            txtNomeAnuncio.setText(anuncio.getNOME_ANUNCIO());
            txtNomeCliente.setText(anuncio.getNOME_CLIENTE());
            txtDataInicio.setText(anuncio.getDATA_INICIO());
            txtDataFim.setText(anuncio.getDATA_FIM());
            txtValorDia.setText(String.format("R$ %.2f", anuncio.getVLR_INVESTIDO_DIA()));
            btnCadCreate.setEnabled(false); //linha para desabilitar o botão adicionar
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadCreate;
    private javax.swing.JButton btnCadDelete;
    private javax.swing.JButton btnCadUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAnuncioPesquisar;
    private javax.swing.JTextField txtDataFim;
    private javax.swing.JTextField txtDataInicio;
    private javax.swing.JTextField txtIdAnuncios;
    private javax.swing.JTextField txtNomeAnuncio;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtValorDia;
    // End of variables declaration//GEN-END:variables
}
